version: '3'

services:
      
  node:
    image: leilaalgarve/nodedesafio:prod
    container_name: node     
    ports:
      - 3000:3000    
    stdin_open: true
    tty: true     
    networks:
      - desafio


  ningx:
    image: leilaalgarve/ningxdesafio:prod
    container_name: ningx
    ports:
      - 8080:80
    networks:
      - desafio

  mysql:
    image: leilaalgarve/mysqldesafio:prod
    container_name: mysql
    env_file:
      - mysql/mysql.env
    volumes: 
      - mysqldata:/var/lib/mysql
    networks:
      - desafio


networks:
  desafio:
    driver: bridge

volumes:
  mysqldata: